/*
 * User Management API
 *
 * API для управления пользователями
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type UserCreate struct {
	Name string `json:"name"`

	Email string `json:"email"`

	FriendIds []int32 `json:"friend_ids,omitempty"`
}
